language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@latest
- npm i -g @angular/cli
notifications:
  slack:
    secure: DNCXZq5P4Xx5z9vorHad3a290YysAu2E6ibuoH4MMzMNsyYxc+P1Sc0q/2vFelE3Fy905hWH50PCpbaZB6kWy42McAHmDKaQDW+fJVxMxNA83q2gcvc6aMjUKJ94KM6EUST49h/8TBB7Ef0XMRSPwFZY986uYnJlr8D+toBRIKPqi9DJ/s3U8OoerTqHrwRq35KpJXEjmXGLzJ2MXEZG/zU/7vjFbDUO1Qbk6AG78a+uNSDHJdthbHu+Yt8UeF0I/hsThavPigvsVcxoUxdnVUnZBFjrNp0YPWgxdghJmR10mrjCBIWlHE02hNTxVlcN3nhON4olSBSg7niDDs1w30VzJf+fNignxBZBGEq1JKHnO3u6AWK4bNnrVPHp+kJhV4W4hgJc6kI/CtDeP1dMU/xFytjxvsV7ycY0X4y9ALrHQkOc++BftBhYtnkaYz/ofW9LgKlTQTdx0MRr/HaJfER5xfD10sSLSigaegucmrdTX0z9HjRNgcQh90OEqi57uTUnAxxqDxmFkyljz/OnB9Xz4eYB7JdU5EBEluThL+F8uNZGQio3BDEHmTg6tSsQ5UgJpvyErz1x01arTOcFfs+nwsowIFhhAORyUmh7EfpEEppsNTzRmrJrEYmnRJP1N+et5yK3IBhzTH1J325RzqkXAjvNS77CKoFnw8AWPWM=
    on_success: change
    on_failure: always
